### ISSUE TITLE
Hello ^^

### ISSUE THREAD

**Issue by stake2** [Muzi-Chan/MonikAI#5]
Are you the person in charge of this fork of MonikAI right now?
I wanted to know cause I would like to help you, and also to ask how things have been, what have you done recently in the software?

**Comment by bernardg12** [comment]
Sorry not the person in charge

**Comment by Muzi-Chan** [comment]
Hey !! ^^
Yeah, I'm the one in charge of this fork 
I think I've changed things a lot, since I'm redoing it from scratch, for letting Monika being crossplatform, running on Windows MacOS and Linux
It's hard, but I think I manage things, and I can still give up on crossplatform for now and taking the C# back whenever I want

And if you want to help, I would be glad UwU

In fact, I've checked you profile, and I was about to try if it would be easier on Python than C++, and that'll be perfect, because you're a Python dev too ^°^

Also, I've seen you wanted to do a Renpy project with someone, you can help me with my Katawa Shoujo Mod Template, it's one of my repo :D
